### ISSUE TITLE
Multiple L3 Interfaces are getting configured with same IP address

### ISSUE THREAD

**Issue by chandrasheker** [Juniper/warp17#10]
**./warp17-master/src/tpg_test_mgmt_api.c** line number 594. Re check the logic of FOR loop for detecting duplicate IP.

Please find the log:

warp17> add tests l3_intf port 0 ip 10.0.0.253 mask 255.255.255.0
L3 interface successfully added.
warp17> add tests l3_intf port 0 ip 10.0.0.253 mask 255.255.255.0
L3 interface successfully added.
warp17> add tests l3_intf port 0 ip 10.0.0.253 mask 255.255.255.0
L3 interface successfully added.
warp17> add tests l3_intf port 0 ip 10.0.0.253 mask 255.255.255.0
L3 interface successfully added.

**Comment by dceara** [comment]
Fixed by commit https://github.com/Juniper/warp17/commit/31b92f1d25d68e3140f0b24fabd8db329d2a64a0. Will be available in release 1.3.
