### ISSUE TITLE
Unable to start two test cases in async mode as mentioned in test_3_http_multiple.cfg 

### ISSUE THREAD

**Issue by chandrasheker** [Juniper/warp17#11]
We tried running WARP17 with cmd-file tests_3_http_multiple.cfg as input to start two test cases in parallel but when we see port stats using "show tests ui"  it is showing that TcId 0 State as running and TcId 1 state as IDLE.

**Comment by dceara** [comment]
Fixed by commit 27ee80c651fe6d7c845f91ebdac2b016b2d39c9f. Will be available in release 1.4.
