### ISSUE TITLE
User Interface Question

### ISSUE THREAD

**Issue by redbeardmeric** [Juniper/warp17#124]
Specifically, what is the category "SW"?

**Comment by davvore33** [comment]
those are the statistics based on the traffic from the point of view of the software level (L5) [code: [dev/common/src/tpg_test_stats.c#L864](https://github.com/Juniper/warp17/blob/dev/common/src/tpg_test_stats.c#L864) ]

**Comment by redbeardmeric** [comment]
Thank you for the clarification!
