### ISSUE TITLE
problem with FIN retransmit

### ISSUE THREAD

**Issue by konstantin-ananyev** [Juniper/warp17#15]
In tsm_SF_fin_wait_I() you send a FIN packet and increment  tcb_snd.nxt.
So when FIN is re-transmitted later (by RTO) all new FINs have seq number greater by one
then initial FIN.
So for the peer system, if first FIN was lost it looks like there is still a 1B gap in the receive sequence,
and session might not be closed properly.
Below is a patch I used to fix the issue.
It is not a proper fix, just a quick and dirty one to cure situation.
Thanks
Konstantin

diff --git a/src/tpg_tcp_sm.c b/src/tpg_tcp_sm.c
index ee069eb..d968a1c 100644
--- a/src/tpg_tcp_sm.c
+++ b/src/tpg_tcp_sm.c
@@ -1606,7 +1606,9 @@ static int tsm_SF_fin_wait_I(tcp_control_block_t *tcb, tcpEvent_t event,
         /* TODO: actually resend data here. */

         /* Resend the FIN. */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_FIN_FLAG | TCP_ACK_FLAG);
+        tcb->tcb_snd.nxt++;
         tsm_schedule_retransmission(tcb);
         break;
     case TE_ORPHAN_TIMEOUT:
@@ -1923,7 +1925,9 @@ static int tsm_SF_last_ack(tcp_control_block_t *tcb, tcpEvent_t event,

         /* Resend the packet that got us here.. */
         /* Send <SEQ=SND.NXT><ACK=RCV.NXT><CTL=FIN,ACK> */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_ACK_FLAG | TCP_FIN_FLAG);
+        tcb->tcb_snd.nxt++;
         /* TODO: anything else to resend here?. */
         tsm_schedule_retransmission(tcb);
         break;
@@ -2084,7 +2088,9 @@ static int tsm_SF_closing(tcp_control_block_t *tcb, tcpEvent_t event,
         }

         /* TODO: actually resend data here (resend FIN|ACK??). */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_FIN_FLAG | TCP_ACK_FLAG);
+        tcb->tcb_snd.nxt++;
         tsm_schedule_retransmission(tcb);
         break;
     case TE_ORPHAN_TIMEOUT:
@@ -2352,7 +2358,9 @@ static int tsm_SF_close_wait(tcp_control_block_t *tcb, tcpEvent_t event,
         tsm_retrans_data(tcb);

         /* Resend <SEQ=SND.NXT><ACK=RCV.NXT><CTL=FIN,ACK> */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_FIN_FLAG | TCP_ACK_FLAG);
+        tcb->tcb_snd.nxt++;
         break;
     case TE_ORPHAN_TIMEOUT:
     case TE_FIN_TIMEOUT:
$ cat patches/p1
diff --git a/src/tpg_tcp_sm.c b/src/tpg_tcp_sm.c
index ee069eb..d968a1c 100644
--- a/src/tpg_tcp_sm.c
+++ b/src/tpg_tcp_sm.c
@@ -1606,7 +1606,9 @@ static int tsm_SF_fin_wait_I(tcp_control_block_t *tcb, tcpEvent_t event,
         /* TODO: actually resend data here. */

         /* Resend the FIN. */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_FIN_FLAG | TCP_ACK_FLAG);
+        tcb->tcb_snd.nxt++;
         tsm_schedule_retransmission(tcb);
         break;
     case TE_ORPHAN_TIMEOUT:
@@ -1923,7 +1925,9 @@ static int tsm_SF_last_ack(tcp_control_block_t *tcb, tcpEvent_t event,

         /* Resend the packet that got us here.. */
         /* Send <SEQ=SND.NXT><ACK=RCV.NXT><CTL=FIN,ACK> */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_ACK_FLAG | TCP_FIN_FLAG);
+        tcb->tcb_snd.nxt++;
         /* TODO: anything else to resend here?. */
         tsm_schedule_retransmission(tcb);
         break;
@@ -2084,7 +2088,9 @@ static int tsm_SF_closing(tcp_control_block_t *tcb, tcpEvent_t event,
         }

         /* TODO: actually resend data here (resend FIN|ACK??). */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_FIN_FLAG | TCP_ACK_FLAG);
+        tcb->tcb_snd.nxt++;
         tsm_schedule_retransmission(tcb);
         break;
     case TE_ORPHAN_TIMEOUT:
@@ -2352,7 +2358,9 @@ static int tsm_SF_close_wait(tcp_control_block_t *tcb, tcpEvent_t event,
         tsm_retrans_data(tcb);

         /* Resend <SEQ=SND.NXT><ACK=RCV.NXT><CTL=FIN,ACK> */
+        tcb->tcb_snd.nxt--;
         tcp_send_ctrl_pkt(tcb, TCP_FIN_FLAG | TCP_ACK_FLAG);
+        tcb->tcb_snd.nxt++;
         break;
     case TE_ORPHAN_TIMEOUT:
     case TE_FIN_TIMEOUT:

**Comment by dceara** [comment]
Fixed with commit https://github.com/Juniper/warp17/commit/099f02ac6bf42d9fd9e4af60e63786cdfd5dc119.

Will be available in version 1.4

**Comment by dceara** [comment]
Fixed in v1.4.
