### ISSUE TITLE
warp17 would not stop after completing tests

### ISSUE THREAD

**Issue by krisk0** [Juniper/warp17#16]
With simple .cmd
```
add tests l3_intf port 0 ip <myIP> mask <myMASK>
add tests client tcp port 0 test-case-id 0 src 192.168.5.21 192.168.5.21 sport 10000 10000 dest 10.0.0.253 10.0.0.253 dport 6000 6000
set tests criteria port 0 test-case-id 0 clients-up 100
set tests client raw port 0 test-case-id 0 data-req-plen 100 data-resp-plen 200
start tests port 0
```
warp17 says ```USER1: Port 0, Test Case 0 "PASSED"!```. I need to run automated nightly tests and therefore want warp17 to exit at this point. Unfortunately I don't know a good way of doing this.

How do I tell warp17 to terminate after all tests are done?

**Comment by dceara** [comment]
There's currently no way in the CLI to stop warp17 automatically when all tests are completed.

However, scripting it to stop when it's done is quite easy. You have two options:
- start warp17 with the configuration file and monitor the syslogs on your system for `USER1: Port 0, Test Case 0 "PASSED"!` or failed messages. Once you decide that all tests are done you can safely kill warp17.
- use the Python RPC API supported by warp17 to monitor the state of the tests. An example on how to do that is: https://github.com/Juniper/warp17/blob/master/examples/python/test_1_http_4M.py. More precisely, if you want to check the state of a test you need to execute a `GetTestStatus` RPC call and verify the `client_result.tsr_state` (like in the `check_stats()` function in https://github.com/Juniper/warp17/blob/master/examples/python/test_1_http_4M.py#L240). Once you decide the tests are done you can use the `warp17_stop()` API to cleanup everything and terminate warp17.

Please let me know if you need more help with this.

**Comment by krisk0** [comment]
Thank you. The explanation is clear.
