### ISSUE TITLE
Link Speed calculation

### ISSUE THREAD

**Issue by nithinn** [Juniper/warp17#17]
In function test_display_stats_hdr(), the links speed in bytes is calculated as below:

` link_speed_bytes = (uint64_t)link_info->link_speed * 1024 * 1024 / 8;`

Bit rates are represented in units of 1000 not 1024, for e.g. 1kbps = 1000 bits/sec.

So the link speed calculation must be as below:
` link_speed_bytes = (uint64_t)link_info->link_speed * 1000* 1000 / 8;`

**Comment by dceara** [comment]
Thanks Nithin for the report! Will be fixed as soon as possible.

**Comment by dceara** [comment]
Fixed with commit https://github.com/Juniper/warp17/commit/21d6a45b669b335a61b531fa5040db38696a483b

Will be available in version 1.4

**Comment by dceara** [comment]
Reopening until release 1.4 is available.

**Comment by dceara** [comment]
Fixed in v1.4.
