### ISSUE TITLE
Data Sends per second shown on Warp UI is not calculated properly  for all values of send-rate configured from Warp-CLI commands.

### ISSUE THREAD

**Issue by yogi1990** [Juniper/warp17#20]
Hello WARP Team,

**Setup Details:**
I have setup warp17 (with DPDK 16.04) on one 40G port with 11 cores for client and 11 core server on different machines.I have 1 HTTP Client connection towards 1 server, and my request size is 13000 Bytes

**Working Scenario:**
If I set send-rate in the client configuration file as 500( say any value less than 1000 or any value greater than 1000, but should be multiple of 1000). Data Sends/sec calculated perfectly fine i.e 500 showing on Web-UI at client side in this case(as expected).

**Problematic Scenario:**
If I set send-rate in the client configuration as 1200.  I observed that Data Send/sec is showing as 2000 on Warp-UI at client side. Although the expected Data Send/sec should be 1200 itself.  The existing calculation for Data Send/sec looks wrong. The Calculated Data Send/sec is showing wrong for all values of send-rate configured as greater than 1000 but not multiple of 1000.( say 1200, 1700, 2200 etc).
Transaction per second ( One HTTP request and response) calculated to ~200. Transaction per second at (HTTP application level) calculated as:
( HTTP response count at t2  –  HTTP response at t1) /( t2 –t1)  where t2 and t1 are time in seconds with single client connection.

I would request Team to provide fix for this bug in coming git commits(or release).
I have pasted the client and server configuration file and command issued to start WARP.

**Configuration Files Used:**
**test_client.cfg**
add tests ip_version 4 l3_intf port 0 ip 10.0.0.1 mask 255.255.255.0
add tests l3_gw port 0 gw 10.0.0.253
add tests client ip_version 4 tcp port 0 test-case-id 0 src 10.0.0.1 10.0.0.1 sport 10001 10001 dest 10.0.0.253 10.0.0.253 dport 6001 6001
set tests timeouts port 0 test-case-id 0 init 0
set tests timeouts port 0 test-case-id 0 uptime 30
set tests timeouts port 0 test-case-id 0 downtime 15
set tests criteria port 0 test-case-id 0 run-time 3600
set tests rate port 0 test-case-id 0 send 1200
set tests client http port 0 test-case-id 0 GET google.com /index.html req-size 13000
start tests port 0
show tests ui

**Command triggered to run Warp at client side:**
./build/warp17 -c 0x103 -n 4 -m 10240 -w 0000:05:00.0 -- --qmap 0.0x100 --tcb-pool-sz 1024 --ucb-pool-sz 1024 --cmd-file ./test_client.cfg

**test_server.cfg:**
add tests ip_version 4 l3_intf port 0 ip 10.0.0.253 mask 255.255.255.0
add tests l3_gw port 0 gw 10.0.0.253
add tests server ip_version 4 tcp port 0 test-case-id 0 src 10.0.0.253 10.0.0.253 sport 6001 6001
set tests server http port 0 test-case-id 0 200-OK resp-size 8000
start tests port 0
show tests ui

**Command to run Warp at Server side:**
./build/warp17 -c 0x7FF3 -n 4 -m 10240 -w 0000:05:00.0 -- --qmap 0.0x7FF0 --tcb-pool-sz 1024 --ucb-pool-sz 1 --cmd-file ./test_server.cfg

The link for queries posted on Google Group can be found at link:
[https://groups.google.com/d/msg/warp17/9FMbgS3L5Cg/9A2fS43lBAAJ]

Best Regards,
Yogesh Kumar

**Comment by mrakesha** [comment]
Hi Dumitru,

Just to add one point to this issue, the WARP17 is not sending the exact send rate which is currently configured on WARP17. 

send configured | Actual packets send rate | percent difference
800000               | 770230                             | 3.7
1000000             | 989762                             | 1.02
3700000             | 3449564                           | 6.76
4200000             | 3777018                           | 10.071

Thanks,
Rakesh Mishra

**Comment by dceara** [comment]
Fixed by commit https://github.com/Juniper/warp17/commit/590add4745e757707d1bc45d4d17504eee8ca4aa.

Will be available in v1.5.
