### ISSUE TITLE
TCP Delay Ack feature as described in rfc1122(section 4.2.3.2)

### ISSUE THREAD

**Issue by anandkolli** [Juniper/warp17#21]
Hello Team,
As discussed raising an issue for TCP delay ack feature.

The current version of WARP sends TCP acknowledgment for every segment it receives due to which we are seeing a drop in throughput.
Is there milestone to implement or enhance to support TCP delayed ack mechanism as mentioned in https://tools.ietf.org/html/rfc1122   section 4.2.3.2

Thank & Regards,
Anand

**Comment by dceara** [comment]
Fixed with commit https://github.com/Juniper/warp17/commit/54281ebb6a89617c02b2702cd01ea61ca3063745. Will be available in v1.5
