### ISSUE TITLE
warp17 does not free hugepages on exit

### ISSUE THREAD

**Issue by krisk0** [Juniper/warp17#22]
On start, warp17 version 1.4 takes all available hugepages.

On exit or kill, it does not free them. At least when stoped via 'exit' command on console or with 'pkill warp17'.

This gluttony makes it hard to use warp17 in server/multiuser environment.

**Comment by dceara** [comment]
I assume you mean that the number of free hugepages in /proc/meminfo doesn't show those hugepages as "free". This is most likely a problem with the kernel updating /proc/meminfo. 

However, the pages are free and available for other applications to use once warp17 exits.

For example, on a machine with 96 * 1G huge pages:

```
$ cat /proc/meminfo | grep -i huge
AnonHugePages:         0 kB
HugePages_Total:      96
HugePages_Free:       96
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB

$ ./build/warp17 -c 0x803 -n 4 -m 98304
EAL: Detected 40 lcore(s)
EAL: Probing VFIO support...
[...]
warp17> exit

$ cat /proc/meminfo | grep -i huge
AnonHugePages:         0 kB
HugePages_Total:      96
HugePages_Free:        0    <<< seems like the pages are not freed but it's actually not true :)
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB

# Try to start a different DPDK application and use all the 96 huge pages:

$ /opt/dpdk/x86_64-native-linuxapp-gcc/build/app/test-pmd/testpmd -c 0x803 -n 4 -m 98304 -- -i
EAL: Detected 40 lcore(s)
EAL: Probing VFIO support...
[...]
Port 0 Link Up - speed 40000 Mbps - full-duplex
Port 1 Link Up - speed 40000 Mbps - full-duplex
Done
testpmd>
```

**Comment by krisk0** [comment]
Yes, the memory is available for other applications, after warp17 exits.

dceara, thanks for explanation.
