### ISSUE TITLE
Poll msg error

### ISSUE THREAD

**Issue by guoguo0906** [Juniper/warp17#24]
Hi,WARP Team,
I am a new programmer,recently, I would like to learn something about the WARP17 and how does the DPDK handle the message quickly，but when I run the test script，it will always print an error “(tpg_pktloop.c)Failed to poll for messages,(-22)”,I don't know where is the wrong process and how to solve it ，can you help me?Thanks very much!

**Comment by dceara** [comment]
Hi,

Can you please share some more information? 
What version of WARP17 are you trying out?
What script are you trying to run and what's the exact command line you're using?
What kind of machine are you running it on?

The error you mentioned doesn't appear with that format anywhere in our codebase. Did you make any local changes to the code?

Also, if possible, we prefer using the warp17 google group for questions as they're easier to reply to: https://groups.google.com/forum/#!forum/warp17 

Thanks,
Dumitru
