### ISSUE TITLE
Insufficient memory allocation for default Gateway

### ISSUE THREAD

**Issue by nithinn** [Juniper/warp17#26]
In function route_init(), the variable 'default_gw_per_port' is allocated for one instance'. This cause invalid memory access when multiple ports are used for traffic generation:
For e.g. in function route_v4_nh_lookup() where default_gw_per_port is accessed like this -> default_gw_per_port[port].re_nh.ip_v4;

```
default_gw_per_port = rte_zmalloc("default_gw_per_port",
                                      sizeof(*default_gw_per_port),
                                      0);
```

This should be 
```
default_gw_per_port = rte_zmalloc("default_gw_per_port",
                                     rte_eth_dev_count() * sizeof(*default_gw_per_port),
                                      0);
```

**Comment by dceara** [comment]
Fixed with commit https://github.com/Juniper/warp17/commit/a558103f3d91ed236920347bcea8e4dcebf32a27

Will be available in v1.5
