### ISSUE TITLE
This system does not support AVX2

### ISSUE THREAD

**Issue by bbethell** [Juniper/warp17#35]
AVX is present but not AVX2? I deployed the ova from the website

**Comment by dceara** [comment]
Can you please try to recompile DPDK and Warp17 within your VM? The instructions are here:
https://github.com/Juniper/warp17#install-dpdk-1611

What hypervisor are you using?

**Comment by bbethell** [comment]
Hi,

I originally downloaded your OVA file.

I can have another go at rebuilding it from scratch.

Currently I am useing ESXI 5.5

Kind Regards,

Billy

---- Dumitru Ceara wrote ----


Can you please try to recompile DPDK and Warp17 within your VM? The instructions are here:
https://github.com/Juniper/warp17#install-dpdk-1611

What hypervisor are you using?

**Comment by dceara** [comment]
@bbethell, can you also share the cpu flags in your guest? Did it work after rebuilding from scratch?

```
cat /proc/cpuinfo | grep flags
```
