### ISSUE TITLE
WARP17 send rate issue on AWS VM machines

### ISSUE THREAD

**Issue by mrakesha** [Juniper/warp17#44]
Hi Dumitru and Matteo,

Raising this issue for tracking..

We are trying to send the WARP17 UDP traffic from AWS (Amazon Web Service) VM machines to VSRX, But we don’t see any state full traffic established in both UDP and TCP case.

-	Send rate is 0 as oppose to configured 10k.
-	Established session is showing as 0
-	We only see Client and Server are sending only 1 packet each and then stop.
-	Hence the traffic on DUT does not sustain more than few seconds.

We have conducted the test for both TCP and UDP for the below topology.

Topo 1 :
abdulh-ubuntu1(0000:00:03.0 = ens3) ----------- abdulh-vsrx------------- abdulh-ubuntu1(0000:00:05.0 = ens5)

Topo 2 :
abdulh-ubuntu1(0000:00:03.0 = ens3) ----------- abdulh-vsrx------------- abdulh-ubuntu2(0000:00:03.0 = ens3)

WARP17 release info :
warp17> show version
warp17 v0.13 @11:43:12, Aug 23 2017
warp17>

Ethtool info and OS
root@10:/home/regress# ethtool -i ens6
driver: ixgbevf
version: 2.12.1-k
firmware-version:
expansion-rom-version:
bus-info: 0000:00:06.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
root@10:/home/regress#

root@10:/home/regress# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
root@10:/home/regress#

Product :
-----------
root@10:/home/regress# dmidecode | grep -i "Product"
        Product Name: HVM domU
root@10:/home/regress#

WARP17 CLI :
------------------
/home/ubuntu/warp17-dev-common/build/warp17  --lcores  0@0,1@0,2@1,3@2 -m  30000 -n  1 -- --ucb-pool-sz  20000 

WARP17 Configuration for TOPO#1: [Total 200 sessions]
----------------------------------------------------------------------------

add tests l3_intf port 0 ip 10.0.1.128 mask 255.255.255.0
add tests l3_gw port 0 gw 10.0.1.250

add tests l3_intf port 1 ip 10.0.3.124 mask 255.255.255.0
add tests l3_gw port 1 gw 10.0.3.212

add tests client udp port 0 test-case-id 0 src 10.0.1.128 10.0.1.128 sport 1024 1043 dest 10.0.3.124 10.0.3.124 dport 80 89
set tests rate port 0 test-case-id 0 open 5000
set tests rate port 0 test-case-id 0 close 0
set tests rate port 0 test-case-id 0 send 10000
set tests timeouts port 0 test-case-id 0 init 0
set tests timeouts port 0 test-case-id 0 uptime infinite
set tests client raw port 0 test-case-id 0 data-req-plen 300 data-resp-plen 300
set tests criteria port 0 test-case-id 0 run-time 1200

add tests server udp port 1 test-case-id 0 src 10.0.3.124 10.0.3.124 sport 80 89
set tests criteria port 1 test-case-id 0 run-time 1200
set tests server raw port 1 test-case-id 0 data-req-plen 300 data-resp-plen 300
start tests port 1
start tests port 0

WARP17 Logs :
-----------------------

warp17> show tests ui
warp17>
warp17> show udp statistics
Port 0 UDP statistics:
  Received Packets    :                  200
  Received Bytes      :                61600
  Sent Packets        :                  200
  Sent Bytes          :                60000

  Malloced UCBs       :                    0
  Freed UCBs          :                    0
  Not found UCBs      :                  200
  UCB alloc errors    :                    0

  Invalid checksum    :                    0
  Small mbuf fragment :                    0
  Failed Packets      :                    0

Port 1 UDP statistics:
  Received Packets    :                  200
  Received Bytes      :                61600
  Sent Packets        :                  200
  Sent Bytes          :                60000

  Malloced UCBs       :                  210
  Freed UCBs          :                    0
  Not found UCBs      :                    0
  UCB alloc errors    :                    0

  Invalid checksum    :                    0
  Small mbuf fragment :                    0
  Failed Packets      :                    0

warp17> show link
 rate [Fixed STRING]: show link rate
warp17> show link rate
Port 0: link UP, speed 10Gbps, duplex full(manual), TX: 0.00% RX: 0.00%
Port 1: link UP, speed 10Gbps, duplex full(manual), TX: 0.00% RX: 0.00%
warp17> show memory statistics
Mempool MBUF RX:
  Total Allocated: 2032
  Total Free     : 784400

Mempool MBUF TX HDR:
  Total Allocated: 400
  Total Free     : 523888

Mempool MBUF CLONE:
  Total Allocated: 400
  Total Free     : 786032

Mempool TCB:
  Total Allocated: 0
  Total Free     : 10485758

Mempool UCB:
  Total Allocated: 410
  Total Free     : 20479590

warp17> show port map
Port 0[socket: 0]:
   Core 2[socket:0] (Tx: 0, Rx: 0)

Port 1[socket: 0]:
   Core 3[socket:0] (Tx: 0, Rx: 0)

warp17> show msg statistics
MSG statistics:
  Messages rcvd       :               593225
  Messages sent       :               593221
  Messages polled     :          44296662870

  Messages errors     :                    0
  Messages proc err   :                    0

  Messages allocated  :                    4
  Messages alloc err  :                    0
  Messages freed      :                    4
warp17> show port statistics
Port 0 software statistics:
  Received packets    :                  211
  Received bytes      :                69860

  Sent packets        :                  209
  Sent bytes          :                68778
  Sent failures       :                    0
  RX Ring If failures :                    0

  Simulated failures  :                    0

Port 1 software statistics:
  Received packets    :                  210
  Received bytes      :                69800

  Sent packets        :                  210
  Sent bytes          :                68820
  Sent failures       :                    0
  RX Ring If failures :                    0

  Simulated failures  :                    0

warp17>

DUT statistics :
--------------------

regress@vsrx1# run show security flow session
Session ID: 145622, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1025 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1025;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145623, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1027 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1027;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145624, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1024 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1024;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145625, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1026 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1026;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145626, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1028 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1028;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145627, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1030 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1030;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145628, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1032 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1032;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145629, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1029 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
  Out: 10.0.3.124/80 --> 10.0.1.128/1029;udp, Conn Tag: 0x0, If: ge-0/0/2.0, Pkts: 1, Bytes: 328,

Session ID: 145630, Policy name: default-permit/4, Timeout: 58, Valid
  In: 10.0.1.128/1031 --> 10.0.3.124/80;udp, Conn Tag: 0x0, If: ge-0/0/0.0, Pkts: 1, Bytes: 328,
---(more)---[abort]

[edit]
regress@vsrx1# run show security flow statistics
    Current sessions: 200
    Packets forwarded: 236101
    Packets dropped: 514
    Fragment packets: 0

[edit]
regress@vsrx1# run show security flow statistics
    Current sessions: 200
    Packets forwarded: 236105
    Packets dropped: 518
    Fragment packets: 0

[edit]

Thanks,
Rakesh Mishra

**Comment by dceara** [comment]
@mrakesha: as discussed offline, this is related to AWS tagging all frames before sending them to the VM. VLAN is not supported for now in Warp17 and it causes L4 lookups to fail. If configuring AWS to not tag the frames, an alternative is to patch Warp17 and always disable RSS hash computation in hardware and using a single processing core per port.

**Comment by mrakesha** [comment]
Hi Dumitru,

Thanks Dumitru for identifying the issue. Now it will be with the Amazon support team to remove the vlan tag before sending the packets to the VM.

Regards,
Rakesh Mishra
