### ISSUE TITLE
Bug in calculating TCP bytes sent.

### ISSUE THREAD

**Issue by chandrasheker** [Juniper/warp17#45]
Hi Dumitru,

There is a bug in calculating TCP bytes sent where l2 and l3 header length is also being added into tcp bytes sent(control and data).

Regards,
Chandrasheker M.

**Comment by dceara** [comment]
Fixed by commit https://github.com/Juniper/warp17/commit/59885f708f1e6161029675e1491f7f6a80835d76.

Will be available in v1.5.
