### ISSUE TITLE
Enhancement to change HTTP request count and HTTP response count from uint32 to uint64 to avoid overflow

### ISSUE THREAD

**Issue by chandrasheker** [Juniper/warp17#53]
In http stats it will be good if we can change http_req_cnt and http_resp_cnt from uint32 to uint64 to avoid quick integer overflow in longer runs.

**Comment by dceara** [comment]
Fixed by commit https://github.com/Juniper/warp17/commit/a376a3354c80616f7c225b651f6ce3e7d52a14dd.

Will be available in v1.5
