### ISSUE TITLE
Failed to allocate TCB after restart tests

### ISSUE THREAD

**Issue by jlijian3** [Juniper/warp17#56]
`warp17 v1.4`
`dpdk 16.11`
`hugepage 1GB x 32`
Command:
`./build/warp17 -c 0000fff0 -n 8 -- --cmd-file cmd_http.cfg`
The cmd_http.cfg is copy from examples/test_6_http_40M_sessions.cfg.
All going well. Then I stopped tests and changed some params.
`stop tests port 0`
`set tests rate port 0 test-case-id 0 send infinite`
`start tests port 0`
USER1 [6:test_case_init_tcp_clients()] Failed to allocate TCB.
USER1 [6:test_case_init_tcp_clients()] Failed to allocate TCB.
USER1 [6:test_case_init_tcp_clients()] Failed to allocate TCB.
USER1 [6:test_case_init_tcp_clients()] Failed to allocate TCB.
USER1 [6:test_case_init_tcp_clients()] Failed to allocate TCB.

**Comment by dceara** [comment]
@jlijian3 `test_6_http_40M_sessions.cfg` will create 40M TCP sessions (i.e., 40M TCP clients on port 0 and 40M TCP servers on port 1). For each TCP endpoint Warp17 uses one TCB (TCP control block) structure. By default the maximum number of TCBs available in the mempool is 10M. You need to increase the TCB pool size to 80M. To do that you can change your cmdline to:

`./build/warp17 -c 0000fff0 -n 8 -- --tcb-pool-sz 80000 --cmd-file cmd_http.cfg`

However, 32G hugepage memory is not enough for 80M TCBs. You will need to use at least 50G hugepage memory.

Also, the reason why you don't see the allocation error logs on the first run is that the `test_6_http_40M_sessions.cfg` config will also bring up the UI immediately. When in the UI the logs are not printed on the console anymore (nevertheless logs are always sent to the system logger regardless of the mode Warp17 is in).

When a test is started, Warp17 tries to preallocate the control blocks for all the client connections that would be generated. Once it can't allocate anymore the log message is generated. However, clients that were successfully allocated will be started according to the test config.
