### ISSUE TITLE
prevent packet drop for low sessons and rate, while using maximum core

### ISSUE THREAD

**Issue by mrakesha** [Juniper/warp17#58]
Hi Dumitru,

Raising this issue for tracking .

1. We want to use maximum cpu cores available on the warp17 machine and still should able to push the traffic as small as hundreds or thousands or millions without any drop.

or

Is it possible to have a mechanism of calculating the number of cores (approximate) required for a particular test based on  sessions and rates. (~10 % of tolerance should be fine).

Thanks,
Rakesh mishra

**Comment by dceara** [comment]
Fixed by commit https://github.com/Juniper/warp17/commit/be260188e9f70ec2e8ae4a549688e70f90182677.

Will be available in v1.6.
