### ISSUE TITLE
Compile issue in warp17-1.7

### ISSUE THREAD

**Issue by vergorun** [Juniper/warp17#62]
Hello, I'm trying to build warp17 1.7 release and get the following error:

  CC tpg_test_mgmt_api.o
/opt/warp17-1.7/src/tpg_test_mgmt_api.c: In function ‘test_mgmt_set_vlan_sockopt’:
/opt/warp17-1.7/src/tpg_test_mgmt_api.c:1556:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (opts->has_vlanso_id)
     ^~
/opt/warp17-1.7/src/tpg_test_mgmt_api.c:1558:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
         old_opts.vlanso_pri = opts->vlanso_pri;
         ^~~~~~~~
cc1: all warnings being treated as errors
/usr/local/share/dpdk/mk/internal/rte.compile-pre.mk:138: recipe for target 'tpg_test_mgmt_api.o' failed
make[2]: *** [tpg_test_mgmt_api.o] Error 1
/usr/local/share/dpdk/mk/rte.extapp.mk:42: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/warp17-1.7'
Makefile:72: recipe for target 'all' failed
make: *** [all] Error 2

I found that in tpg_test_mgmt_api.c in function test_mgmt_set_vlan_sockopt missed brackets after statement `if (opts->has_vlanso_id)`

**Comment by dceara** [comment]
Fixed by https://github.com/Juniper/warp17/commit/c3dd878de73fe31e2ab3a8a6c160b436a1ced1cb.

Will be available in v1.8. Until then the `dev/common` branch contains the fix.
