### ISSUE TITLE
ERROR: Rings PMD doesn't support vlan/ipv4/udp/tcp rx capabilities!

### ISSUE THREAD

**Issue by SSam009** [Juniper/warp17#65]
wrong forum, will post into google group.

**Comment by JQLSS** [comment]
wrong forum, will post into google group.

**Comment by davvore33** [comment]
Hi @JQLSS I've reopened this issue because we need it in order to better track our issues, thanks for reporting, I'm already on it

**Comment by SSam009** [comment]
Thank you so much, I was able to run  Rings PMD with the latest code.

**Comment by davvore33** [comment]
Fixed by c400f9b649a8eaded125589de1c62b1de33355d4

Will be available in v1.8. Until then the dev/common branch contains the fix.
