### ISSUE TITLE
Warp17 is  failing to initialize X710 port 

### ISSUE THREAD

**Issue by SSam009** [Juniper/warp17#70]
warp is failing to initialize "Ethernet Controller X710 for 10GbE SFP+"  NICs.  It seems known issue and fixed in warp 1.5 ( https://github.com/Juniper/warp17/issues/42).  But it's still failing with latest code. 

Here is my system config 
warp17-dev-common
dpdk-stable-16.11.4

[root@test]# ./dpdk-devbind.py  --status 

Network devices using DPDK-compatible driver
============================================
0000:05:00.0 'Ethernet Controller X710 for 10GbE SFP+' drv=igb_uio unused=
0000:05:00.1 'Ethernet Controller X710 for 10GbE SFP+' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:02:00.0 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eno1 drv=tg3 unused=igb_uio 
0000:02:00.1 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eno2 drv=tg3 unused=igb_uio *Active*
0000:02:00.2 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eno3 drv=tg3 unused=igb_uio 
0000:02:00.3 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eno4 drv=tg3 unused=igb_uio 
0000:08:00.0 'MT27700 Family [ConnectX-4]' if=ens1 drv=mlx5_core unused=igb_uio *Active*
0000:82:00.0 'MT27700 Family [ConnectX-4]' if=ens3 drv=mlx5_core unused=igb_uio *Active*

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>
[root@test]#  

[root@test warp17-dev-common]# /build/warp17 -c 0xFF -n 4  -w 05:00.0 -w 05:00.1 -- --qmap-default max-c  --cmd-file test.cfg  
EAL: Detected 56 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1572 net_i40e
PMD: eth_i40e_dev_init(): FW 5.0 API 1.5 NVM 05.00.04 eetrack 80002530
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1572 net_i40e
PMD: eth_i40e_dev_init(): FW 5.0 API 1.5 NVM 05.00.04 eetrack 80002530
warp17> USER1: Creating mempool global_cfg_mbuf-0 on core 0(size: 1024, obj_size: 2304, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf-2 on core 2(size: 131072, obj_size: 2304, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_tx_hdr-2 on core 2(size: 87381, obj_size: 326, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_clone-2 on core 2(size: 131072, obj_size: 128, priv: 4 cache: 512)
USER1: Creating mempool tcb_pool-2 on core 2(size: 1747626, obj_size: 312, priv: 0 cache: 0)
USER1: Creating mempool ucb_pool-2 on core 2(size: 1747626, obj_size: 200, priv: 0 cache: 0)
USER1: Creating mempool global_pkt_mbuf-3 on core 3(size: 131072, obj_size: 2304, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_tx_hdr-3 on core 3(size: 87381, obj_size: 326, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_clone-3 on core 3(size: 131072, obj_size: 128, priv: 4 cache: 512)
USER1: Creating mempool tcb_pool-3 on core 3(size: 1747626, obj_size: 312, priv: 0 cache: 0)
USER1: Creating mempool ucb_pool-3 on core 3(size: 1747626, obj_size: 200, priv: 0 cache: 0)
USER1: Creating mempool global_pkt_mbuf-4 on core 4(size: 131072, obj_size: 2304, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_tx_hdr-4 on core 4(size: 87381, obj_size: 326, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_clone-4 on core 4(size: 131072, obj_size: 128, priv: 4 cache: 512)
USER1: Creating mempool tcb_pool-4 on core 4(size: 1747626, obj_size: 312, priv: 0 cache: 0)
USER1: Creating mempool ucb_pool-4 on core 4(size: 1747626, obj_size: 200, priv: 0 cache: 0)
USER1: Creating mempool global_pkt_mbuf-5 on core 5(size: 131072, obj_size: 2304, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_tx_hdr-5 on core 5(size: 87381, obj_size: 326, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_clone-5 on core 5(size: 131072, obj_size: 128, priv: 4 cache: 512)
USER1: Creating mempool tcb_pool-5 on core 5(size: 1747626, obj_size: 312, priv: 0 cache: 0)
USER1: Creating mempool ucb_pool-5 on core 5(size: 1747626, obj_size: 200, priv: 0 cache: 0)
USER1: Creating mempool global_pkt_mbuf-6 on core 6(size: 131072, obj_size: 2304, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_tx_hdr-6 on core 6(size: 87381, obj_size: 326, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_clone-6 on core 6(size: 131072, obj_size: 128, priv: 4 cache: 512)
USER1: Creating mempool tcb_pool-6 on core 6(size: 1747626, obj_size: 312, priv: 0 cache: 0)
USER1: Creating mempool ucb_pool-6 on core 6(size: 1747626, obj_size: 200, priv: 0 cache: 0)
USER1: Creating mempool global_pkt_mbuf-7 on core 7(size: 131072, obj_size: 2304, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_tx_hdr-7 on core 7(size: 87381, obj_size: 326, priv: 4 cache: 512)
USER1: Creating mempool global_pkt_mbuf_clone-7 on core 7(size: 131072, obj_size: 128, priv: 4 cache: 512)
USER1: Creating mempool tcb_pool-7 on core 7(size: 1747626, obj_size: 312, priv: 0 cache: 0)
USER1: Creating mempool ucb_pool-7 on core 7(size: 1747626, obj_size: 200, priv: 0 cache: 0)
USER1: Found 2 Ethernet ports to start.
USER1: [port_setup_port()] Initializing Ethernet port 0.
USER1: Ethernet port 0 initialized with MAC address 3C:FD:FE:A3:F1:58
PMD: i40e_pf_config_rss(): Max of contiguous 3 PF queues are configured
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
PMD: i40e_pf_config_rss(): Max of contiguous 3 PF queues are configured
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
USER1: [port_setup_port()] Initializing Ethernet port 1.
USER1: Ethernet port 1 initialized with MAC address 3C:FD:FE:A3:F1:59
PMD: i40e_pf_config_rss(): Max of contiguous 3 PF queues are configured
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
PMD: i40e_pf_config_rss(): Max of contiguous 3 PF queues are configured
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
USER1: WARNING: Ethernet port 1 is DOWN at init!
USER1: Started 2 Ethernet ports.
USER1: Starting test management loop on lcore 1, core index 1
USER1: Starting receive packet loop on lcore 3, core index 3
USER1: Starting receive packet loop on lcore 4, core index 4
USER1: Starting receive packet loop on lcore 6, core index 6
USER1: Starting receive packet loop on lcore 2, core index 2
USER1: Starting receive packet loop on lcore 5, core index 5
USER1: Starting receive packet loop on lcore 7, core index 7
#PORT 0 - client port
#PORT 1 - server port

add tests l3_intf port 0 ip 100.64.18.7 mask 255.255.255.254
L3 interface successfully added.
add tests l3_gw port 0 gw 100.64.18.6
Default gateway successfully added.

add tests client tcp port 0 test-case-id 0 src 130.1.255.10 130.1.255.255 sport 1000 2000 dest 100.64.200.10 100.64.200.10 dport 80 80
Test case 0 successfully added to port 0!

set tests timeouts port 0 test-case-id 0 init 0
Port 0, Test Case 0 updated!
set tests timeouts port 0 test-case-id 0 uptime 5
Port 0, Test Case 0 updated!
set tests timeouts port 0 test-case-id 0 downtime 1
Port 0, Test Case 0 updated!

set tests rate port 0 test-case-id 0 open 1000000
Port 0, Test Case 0 updated!
set tests rate port 0 test-case-id 0 send  900000
Port 0, Test Case 0 updated!
#set tests rate port 0 test-case-id 0 open 100
#set tests rate port 0 test-case-id 0 send  9

set tests criteria port 0 test-case-id 0 run-time 400
Port 0, Test Case 0 updated!
set tests client http port 0 test-case-id 0 GET google.com /index.html req-size 64
Port 0, Test Case 0 updated!

# Server configuration
add tests l3_intf port 1 ip 100.64.18.9 mask 255.255.255.254
L3 interface successfully added.
add tests l3_gw port 1 gw 100.64.18.8
Default gateway successfully added.

add tests server tcp port 1 test-case-id 0 src 135.0.0.5 135.0.0.5 sport 80 80
Test case 0 successfully added to port 1!
set tests server http port 1 test-case-id 0 200-OK resp-size 20
Port 1, Test Case 0 updated!

start tests port 1
ERROR: Ehernet port 1: Link down!
start tests port 0
USER1: Test Case 0 started on port 0
Tests started on port 0
show tests ui

warp17>

**Comment by dceara** [comment]
Hi @SSam009,

Looks like the port is initialized properly:

```
USER1: Found 2 Ethernet ports to start.
USER1: [port_setup_port()] Initializing Ethernet port 0.
USER1: Ethernet port 0 initialized with MAC address 3C:FD:FE:A3:F1:58
PMD: i40e_pf_config_rss(): Max of contiguous 3 PF queues are configured
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
PMD: i40e_pf_config_rss(): Max of contiguous 3 PF queues are configured
USER1: WARNING: Sleeping for 10 seconds in order to avoid i40e FW sync issues!
USER1: [port_setup_port()] Initializing Ethernet port 1.
USER1: Ethernet port 1 initialized with MAC address 3C:FD:FE:A3:F1:59
```

But DPDK reports the link DOWN:
```
USER1: WARNING: Ethernet port 1 is DOWN at init!
```

Are the two ports connected to a DUT? Or are they connected back to back? If there's a DUT can you please double check the link status on the DUT?

**Comment by SSam009** [comment]
@dceara , I am sorry it was my mistake, eth1 not connected to DTU.  We have fixed the connectivity issue,  it's working good.
