### ISSUE TITLE
The current warp17 builds are not backward compatible with  DPDK  16.11.2. 

### ISSUE THREAD

**Issue by mrakesha** [Juniper/warp17#80]
Hi Matteo and Dumitru,

Is it possible to make the current warp17 DCB or Master builds backward compatible to DPDK 16.11.2 as well (along with DPDK 17.3).
You can very well ignore this issue if its more complex nature or more time taking.

Please find the error message while trying to install the warp17 on machine esst-srv32 :

make[1]: Entering directory '/root/WARP17/warp17-dev-common/api'
  PC-C warp17-common.proto
  PC-PY warp17-common.proto
  PC-XLATE warp17-common.proto
  PC-C warp17-l3.proto
  PC-PY warp17-l3.proto
  PC-XLATE warp17-l3.proto
  PC-C warp17-app-raw.proto
  PC-PY warp17-app-raw.proto
  PC-XLATE warp17-app-raw.proto
  PC-C warp17-app-http.proto
  PC-PY warp17-app-http.proto
  PC-XLATE warp17-app-http.proto
  PC-C warp17-app.proto
  PC-PY warp17-app.proto
  PC-XLATE warp17-app.proto
  PC-C warp17-client.proto
  PC-PY warp17-client.proto
  PC-XLATE warp17-client.proto
  PC-C warp17-server.proto
  PC-PY warp17-server.proto
  PC-XLATE warp17-server.proto
  PC-C warp17-test-case.proto
  PC-PY warp17-test-case.proto
  PC-XLATE warp17-test-case.proto
  PC-C warp17-sockopt.proto
  PC-PY warp17-sockopt.proto
  PC-XLATE warp17-sockopt.proto
  PC-C warp17-stats.proto
  PC-PY warp17-stats.proto
  PC-XLATE warp17-stats.proto
  PC-C warp17-service.proto
  PC-PY warp17-service.proto
  PC-XLATE warp17-service.proto
make[1]: Leaving directory '/root/WARP17/warp17-dev-common/api'
make[1]: Entering directory '/root/WARP17/warp17-dev-common'
  CC tpg_arp.o
In file included from /root/WARP17/warp17-dev-common/src/tpg_arp.c:75:0:
/root/WARP17/warp17-dev-common/inc/tcp_generator.h:78:25: fatal error: rte_bus_pci.h: No such file or directory
compilation terminated.
/usr/local/share/dpdk/mk/internal/rte.compile-pre.mk:138: recipe for target 'tpg_arp.o' failed
make[2]: *** [tpg_arp.o] Error 1
/usr/local/share/dpdk/mk/rte.extapp.mk:42: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/WARP17/warp17-dev-common'
Makefile:72: recipe for target 'all' failed
make: *** [all] Error 2
root@esst-srv32:~/WARP17/warp17-dev-common# cd ../

Thanks,
Rakesh Mishra

**Comment by davvore33** [comment]
Hi @mrakesha,
I'm sorry but dpdk17 isn't actually retro compatible
