### ISSUE TITLE
raw latency configuration issues in traffics 

### ISSUE THREAD

**Issue by Fy45** [Juniper/warp17#87]
Hi,
I am using the latest version of  warp17. And I use dpdk-16.11.7, the operating system is Ubuntu server 14.04 LTS and the driver of NICs are virtio.

When I studied your example of raw_latency.cfg and apply the command into my configurations, but when I run the scripts it always warning me for the problem that 

**WARNING: Seting latency option without RX timestamping enabled in test case 0 config on port 1**, despite the fact that I did run the 

_set tests server raw port 1 test-case-id 0 data-req-plen 64 data-resp-plen 16 rx-timestamp tx-timestamp_ and got the right return message.

Also in the case above, I set up the data rate at 700000 try to reach my machine's limits. However as long as I enable the latency measurement with _data-resp-plen 16_ the data send rate will no longer higher than ~5000, I am not sure if there something wrong with my configuration or the speed I set is too high.

**Comment by Fy45** [comment]
Also, I want to know if the connection set up by warp17 allows the multi-threads like in 5000 flows and how I can achieve that?

Thanks in advance!
BR,
Yuan.

**Comment by dceara** [comment]
Answered on the [mailing list](https://groups.google.com/forum/#!topic/warp17/lLf79sn60s4). 

@davvore33 can you please look into fixing the check that triggers the warning message? It's just a display issue.
