### ISSUE TITLE
spelling mistake in test_6_http_40M_sessions.cfg

### ISSUE THREAD

**Issue by chandrasheker** [Juniper/warp17#9]
Please check the infinite spelling in test_6_http_40M_sessions.cfg file line number 80.

set tests timeouts port 0 test-case-id 0 uptime infinte
set tests timeouts port 0 test-case-id 0 downtime infinite

**Comment by dceara** [comment]
Thanks. I'll address it in the next release. 

The CLI will fail to execute the command. However, it doesn't affect execution in any way as the default rate limiting is anyway "infinite".

**Comment by chandrasheker** [comment]
:)

**Comment by dceara** [comment]
Fixed by commit https://github.com/Juniper/warp17/commit/6f4822b8b1e6ef41bd94f87f6a3cad427947e2df. 
Will be available in v1.3
